import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import PostComment from './components/PostComment'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <ClerkProvider>
    <html lang="en">

       <body className={`${inter.className}  bg-cyan-300 text-slate-600 container mx-auto p-4`}>{children}
  
       
       </body>
    </html>

    </ClerkProvider>
  )
}
